<a href="https://colab.research.google.com/github/ViktorShalygin/MY_digital_image_processing/blob/main/TF_lab1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Create a vector, scalar, matrix and tensor with values of your choosing using tf.constant().

Find the shape, rank and size of the tensors you created in 1.

Create two tensors containing random values between 0 and 1 with shape [5, 300].

Multiply the two tensors you created in 3 using matrix multiplication.

Multiply the two tensors you created in 3 using dot product.

Create a tensor with random values between 0 and 1 with shape [224, 224, 3].

Find the min and max values of the tensor you created in 6.

Created a tensor with random values of shape [1, 224, 224, 3] then squeeze it to change the shape to [224, 224, 3].

Create a tensor with shape [10] using your own choice of values, then find the index which has the maximum value.

One-hot encode the tensor you created in 9.

Create a vector, scalar, matrix and tensor with values of your choosing using tf.constant().

In [44]:
import numpy as np
import tensorflow as tf
print(tf.__version__)

2.15.0


In [4]:
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [5]:
vector = tf.constant([5, 1])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([5, 1], dtype=int32)>

In [6]:
matrix = tf.constant([[1, 3],
                      [7, 1],
                      [8, 5]])
matrix

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 3],
       [7, 1],
       [8, 5]], dtype=int32)>

In [9]:
tensor = tf.constant([[[1, 2, 3],
                       [4, 5, 6]],
                      [[7, 8, 9],
                       [10, 11, 12]],
                      [[13, 14, 15],
                       [16, 17, 18]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

Find the shape, rank and size of the tensors you created in 1.

In [13]:
tensor.ndim #rank


3

In [22]:
tf.size(tensor) #size


<tf.Tensor: shape=(), dtype=int32, numpy=18>

In [17]:
tensor.shape #shape

TensorShape([3, 2, 3])

Create two tensors containing random values between 0 and 1 with shape [5, 300].

In [21]:
tensor1 = tf.random.uniform(shape=[5, 300], minval=0, maxval=1)
tensor2 = tf.random.uniform(shape=[5, 300], minval=0, maxval=1)
print(tensor1, tensor2, sep='\n')

tf.Tensor(
[[0.27017355 0.98462486 0.5379813  ... 0.6644335  0.49912596 0.16380215]
 [0.6087185  0.8139142  0.02468777 ... 0.3055613  0.45964098 0.42416525]
 [0.868238   0.14700735 0.69728494 ... 0.48084962 0.60565305 0.35957217]
 [0.1113838  0.4235469  0.4465717  ... 0.28648794 0.18334317 0.14078045]
 [0.9644736  0.40748525 0.5974586  ... 0.19272459 0.7027103  0.71361494]], shape=(5, 300), dtype=float32)
tf.Tensor(
[[0.81534874 0.41775727 0.41344    ... 0.516852   0.43869781 0.19267058]
 [0.7772443  0.5537325  0.7444936  ... 0.5106145  0.54215086 0.8286394 ]
 [0.43758774 0.41548228 0.12439251 ... 0.251433   0.41673267 0.5675448 ]
 [0.80161    0.7325294  0.9054084  ... 0.751536   0.4714011  0.02271891]
 [0.9580276  0.3587829  0.5322788  ... 0.56958663 0.00265896 0.32259548]], shape=(5, 300), dtype=float32)


Multiply the two tensors you created in 3 using matrix multiplication. (we cannot due to math rules)

In [25]:
tensor2 = tf.transpose(tensor2)
mult_tensor = tensor1 @ tensor2
print(mult_tensor)

tf.Tensor(
[[77.12694  79.9969   78.840614 79.31313  74.49718 ]
 [76.36983  77.99393  75.8683   76.84995  71.753334]
 [74.77549  78.09977  75.67316  73.06801  73.30423 ]
 [75.72573  77.36978  75.37212  73.03517  76.38952 ]
 [78.13301  78.81376  79.43266  75.02978  77.4245  ]], shape=(5, 5), dtype=float32)


Multiply the two tensors you created in 3 using dot product.

In [28]:
tf.tensordot(tensor1, tensor2, axes = 1)

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[77.12694 , 79.9969  , 78.840614, 79.31313 , 74.49718 ],
       [76.36983 , 77.99393 , 75.8683  , 76.84995 , 71.753334],
       [74.77549 , 78.09977 , 75.67316 , 73.06801 , 73.30423 ],
       [75.72573 , 77.36978 , 75.37212 , 73.03517 , 76.38952 ],
       [78.13301 , 78.81376 , 79.43266 , 75.02978 , 77.4245  ]],
      dtype=float32)>

Create a tensor with random values between 0 and 1 with shape [224, 224, 3].

In [31]:
  tensor_224_224_3 = tf.random.uniform(shape=[224, 224, 3], minval=0, maxval=1)
  print(tensor_224_224_3)

tf.Tensor(
[[[0.04326355 0.6590636  0.8226737 ]
  [0.93935645 0.34841692 0.45878422]
  [0.5275996  0.99055946 0.9056052 ]
  ...
  [0.3360076  0.74700344 0.4735266 ]
  [0.6772361  0.2621106  0.45306432]
  [0.7416823  0.1478355  0.09257209]]

 [[0.60004187 0.753142   0.6916717 ]
  [0.92465913 0.31978655 0.6217489 ]
  [0.42524922 0.8146876  0.54577696]
  ...
  [0.6422409  0.27796638 0.7040514 ]
  [0.50572217 0.51653755 0.19215167]
  [0.10917056 0.86190057 0.8494934 ]]

 [[0.46132433 0.3189745  0.6171372 ]
  [0.8455447  0.5299792  0.00891459]
  [0.58439016 0.58337927 0.80034864]
  ...
  [0.8894911  0.5584552  0.01263881]
  [0.45589948 0.41735446 0.67573166]
  [0.4402938  0.93663764 0.371683  ]]

 ...

 [[0.69191754 0.45309258 0.11777878]
  [0.8658867  0.04063118 0.20742977]
  [0.41866267 0.18981373 0.37876832]
  ...
  [0.7445648  0.49386787 0.5487753 ]
  [0.4200251  0.55637145 0.33493185]
  [0.23417032 0.15249848 0.75008297]]

 [[0.76057565 0.22820687 0.94405496]
  [0.7692183  0.19676518 0

Create a tensor with shape [10] using your own choice of values, then find the index which has the maximum value.

In [45]:
tensor_10 = tf.constant(np.random.randint(low=0, high=100, size=10))
tensor_10


<tf.Tensor: shape=(10,), dtype=int64, numpy=array([94,  8, 59, 77, 16, 15,  5, 51, 90, 59])>

In [48]:
print(f"The maximum value of tensor_10 is at position: {tf.argmax(tensor_10).numpy()}")
print(f"The maximum value of tensor_10 is: {tf.reduce_max(tensor_10).numpy()}")

The maximum value of tensor_10 is at position: 0
The maximum value of tensor_10 is: 94


One-hot encode the tensor you created in 9.

In [52]:
tf.one_hot(tensor_10, depth=10)

<tf.Tensor: shape=(10, 10), dtype=float32, numpy=
array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]], dtype=float32)>